- name: Документация по Kubernetes с поддержкой Azure Arc
  href: index.yml
- name: Обзор
  items:
    - name: Сведения о Kubernetes с поддержкой Arc
      href: overview.md
- name: Практические руководства
  items:
    - name: Подключение к Azure Arc
      items:
        - name: Подключение кластера
          href: connect-cluster.md
        - name: Подключение субъекта-службы
          href: create-onboarding-service-principal.md
    - name: Управление
      items:
        - name: Развертывание конфигураций с использованием GitOps
          href: use-gitops-connected-cluster.md
        - name: Развертывание диаграмм Helm с использованием GitOps
          href: use-gitops-with-helm.md
        - name: Принудительное применение GitOps с помощью службы "Политика Azure"
          href: use-azure-policy.md
        - name: Мониторинг с использованием Azure Monitor для контейнеров
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Применение политик управления допуском с помощью службы "Политика Azure"
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Развертывание рабочих нагрузок для Интернета вещей
          href: deploy-azure-iot-edge-workloads.md
    - name: Устранение неполадок
      href: Troubleshooting.md
- name: Справочник
  items:
    - name: Встроенные компоненты Политики Azure
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
    - name: Azure PowerShell
      href: /powershell/module/Az.ConnectedKubernetes/
- name: Ресурсы
  items:
    - name: "Начало работы с Azure\_Arc"
      href: 'https://azurearcjumpstart.io'